### ISSUE TITLE
templates working?

### ISSUE THREAD

**Issue by daniel-lo** [fishjam/LogViewer#5]
Hi, are the regex templates supposed to be working .. not noticing any change when I toggle them. Cheers

**Comment by fishjam** [comment]
when toggle the template, you should reload the file.

**Comment by daniel-lo** [comment]
I see no reaction

**Comment by fishjam** [comment]
please refer this
  ![image](https://user-images.githubusercontent.com/1870684/134477096-70d70ffd-72d8-4ec3-8155-40b0ca8ac7f6.png)

**Comment by daniel-lo** [comment]
did so

**Comment by fishjam** [comment]
it's very stange.
and there is code, you can download and try. 
or can you provide the screen record?

**Comment by daniel-lo** [comment]
By toggling the profiles I would at least expect a changed view .. regardless of everything being messed up or not .. but as I said .. maybe it notices that the rules don't match and thus doesn't do anything. I wanted to see something move .. before I try to build an ini for my purpose:
![vid](https://user-images.githubusercontent.com/4311558/134815084-f38a7f1d-ea56-4348-adaf-6bf82ee6ad9e.gif)

**Comment by fishjam** [comment]
yes, you have to build your ini according your log format. 
you can refer this https://github.com/fishjam/LogViewer/blob/master/README_CN.md#%E4%BD%BF%E7%94%A8-regex-match-tracer-%E5%88%86%E6%9E%90%E5%92%8C%E7%BC%96%E8%BE%91%E6%AD%A3%E5%88%99%E9%85%8D%E7%BD%AE , it's chinese, but you can translate it by google. 


and you can try this `([\d-:\.]+)\s+([\d-:\.]+)\s+([^:]+):\s+(.*)` for the REGULAR in your ini files.

**Comment by daniel-lo** [comment]
indeed .. now I see a change .. though I must admit I didn't understand the concept yet and what the ini file exactly does. Since I am no programmer I'd like to ask if you could help with the complete ini:

# LogViewer configuration

# ioBroker log:
# 2021-08-30 00:00:09.630  - [32minfo[39m: fitbit-api.0 (1528) Terminated (NO_ERROR): Without reason

[COMMON]
REGULAR=([\d-:\.]+)\s+([\d-:\.]+)\s+([^:]+):\s+(.*)

#Date Time Format, now only support these formats:
#   yyyy-MM-dd HH:mm:ss.SSS
#   yyyy-MM-dd HH:mm:ss
#   HH:mm:ss.SSS
#   HH:mm:ss

TIME_FORMAT=yyyy-MM-dd HH:mm:ss.SSS

[REGMAP]
ITEM_TIME=$1
ITEM_LEVEL=$5
ITEM_PID=$3
ITEM_TID=$4
ITEM_MODULE=$6
ITEM_FUN=
ITEM_LOG=$7

[LEVELMAP]
LEVEL_debug=debug
LEVEL_info=Info
LEVEL_warn=warn
LEVEL_error=error
