### ISSUE TITLE
please help to write regex for nlog or log4net

### ISSUE THREAD

**Issue by asine** [fishjam/LogViewer#7]
log file is：2021-11-17 14:04:28.9834|INFO|Topshelf.HostFactory|Configuration Result:
[Success] Name aaaaar
[Success] DisplayName aaaaa
[Success] Description ggggg
[Success] ServiceName bbbbb

it separate by "|",I write REGULAR=^*\|
but logviewer say error

**Comment by fishjam** [comment]
you can try this:
```
  REGULAR=([^|]*)\|([^|]*)\|([^|]*)\|([^|]*)
```
And REGMAP is( others are empty)
```
ITEM_TIME=$1
ITEM_LEVEL=$2
ITEM_MODULE=$3
ITEM_LOG=$4
```

notice:
  - 1. logviewer analyze each `LINE` as a log record, so if there are any '\r' or '\n' , it will be treat same as previous record. 
  - 2. you can refer [this](https://github.com/fishjam/LogViewer#use-regex-match-tracer-to-analyze-and-edit-regular-configurations) to analyze and write your owner regex.

**Comment by asine** [comment]
thanks,it work
