### ISSUE TITLE
An error occurred while loading the archive

### ISSUE THREAD

**Issue by hififish** [fishjam/LogViewer#8]
While opening the LogViewer.exe, it says, "an error occurred while loading the archive", and there is nothing in the window. How to solve it, please?

**Comment by fishjam** [comment]
can you provide error screenshot?

**Comment by hififish** [comment]
> 你能提供错误截图吗？

![image](https://user-images.githubusercontent.com/82586741/206839687-45691a1e-83f3-43bd-949e-89d5064cdb76.png)

**Comment by hififish** [comment]
![image](https://user-images.githubusercontent.com/82586741/206839854-e117b72b-25d5-4f43-86c0-69a33c467a03.png)

**Comment by fishjam** [comment]
This application si windows program, not for linux. 
If you want use in linux, you can try use wine, but I'm not sure it can work.
