### ISSUE TITLE
Can logviewer support some new time-format？

### ISSUE THREAD

**Issue by wzhmei** [fishjam/LogViewer#9]
such as ：yyyy/mm/dd hh:mm:ss.SSS
and
yyyy/mm/dd hh:mm:ss.SSSSSSSSS 
tips: SSSSSSSSS is for high precision clock
Thanks

**Comment by wzhmei** [comment]
I have tested for 2 time-formats:
1, when I set TIME_FORMAT and DISPLAY_TIME_FORMAT =yyyy-mm-dd hh:mm:ss.SSSSSSSSS
 2022-09-07 23:34:45:123456789  --- work

2, when I set TIME_FORMAT and DISPLAY_TIME_FORMAT =yyyy/mm/dd hh:mm:ss.SSSSSSSSS
 2022/09/07 23:34:45:123456789  --- not work

Please check. Thanks!

**Comment by fishjam** [comment]
updated. you can try again.
you can set TIME_FORMAT=yyyy-mm-dd hh:mm:ss.SSSSSSSSS and delete DISPLAY_TIME_FORMAT ,

**Comment by wzhmei** [comment]
when I set TIME_FORMAT=yyyy/mm/dd hh:mm:ss.SSSSSSSSS
content in logfile： 2022/09/07 23:34:45.123456789 ，it works ， but it shows “ 2022-09-07 23:34:45.123456789” . 

Anyway, it works, thanks!

**Comment by fishjam** [comment]
complete and close it.
